apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log
  template:
    metadata:
      labels:
        app: log
    spec:
      containers:
      - name: log
        image: bwomack/log:latest
        ports:
        - containerPort: 30081

---
apiVersion: v1
kind: Service
metadata:
  name: log-service
spec:
  type: NodePort
  selector:
    app: log
  ports:
    - protocol: TCP
      port: 30081
      targetPort: 30081
      nodePort: 30081